version: '3.8'

services:
  
  # if using postgresql on local machine
  # db:
  #   image: postgres:latest
  #   container_name: postgres_db
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "5432:5432"
  
  flask_api:
    build: .
    container_name: flask_api
    restart: always
    # Use depends_on only when using the above db service
    # depends_on:
    #   - db
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:57236/${DATABASE_NAME}
    ports:
      - "8080:8080"