name: Flask CI/CD

on:
  push:
    branches:
      - main # Trigger pipeline when there is commit to the "main" branch
  pull_request:
    branches:
      - main # Trigger pipeline when there is pull request to the "main" branch

jobs:
  test:
    runs-on: ubuntu-latest # Run ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Clone repo into runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.21"

      - name: Install dependencies # Install dependencies of app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests # Run Pytest to checkout code

      - name: Install frontend validation tools
        run: |
          npm install -g eslint

      - name: Test JavaScript
        run: eslint --config eslint/eslint.config.js assets/js/

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Validate Docker Compose syntax
        run: docker-compose config

      - name: Start containers
        run: docker-compose up -d

      - name: Check running containers
        run: docker ps

      - name: Check Flask API logs
        run: docker logs flask_api # Check the log to confirm Flask connects to the database correctly
